<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;
use App\Models\ProductImage;
use Illuminate\Support\Str;

class AdditionalProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $additionalProducts = [
            // Electronics & Mobile Phones
            [
                'name' => 'OnePlus 12 Pro',
                'slug' => 'oneplus-12-pro',
                'description' => 'Flagship killer with Hasselblad camera system and 100W fast charging',
                'short_description' => '6.7" AMOLED, 50MP Hasselblad, Snapdragon 8 Gen 3',
                'sku' => 'ONEPLUS-12P-256',
                'price' => 85000.00,
                'compare_price' => 95000.00,
                'stock_quantity' => 35,
                'weight' => 0.208,
                'category_slug' => 'mobile-phones',
            ],
            [
                'name' => 'Google Pixel 8 Pro',
                'slug' => 'google-pixel-8-pro',
                'description' => 'AI-powered smartphone with advanced computational photography',
                'short_description' => '6.7" LTPO OLED, 50MP camera, Tensor G3',
                'sku' => 'GOOGLE-PIX8P-256',
                'price' => 95000.00,
                'compare_price' => 105000.00,
                'stock_quantity' => 25,
                'weight' => 0.215,
                'category_slug' => 'mobile-phones',
            ],
            [
                'name' => 'Xiaomi 14 Ultra',
                'slug' => 'xiaomi-14-ultra',
                'description' => 'Premium smartphone with Leica optics and 120W charging',
                'short_description' => '6.73" AMOLED, 50MP Leica, Snapdragon 8 Gen 3',
                'sku' => 'XIAOMI-14U-512',
                'price' => 75000.00,
                'compare_price' => 85000.00,
                'stock_quantity' => 30,
                'weight' => 0.229,
                'category_slug' => 'mobile-phones',
            ],
            
            // Laptops
            [
                'name' => 'Dell XPS 15',
                'slug' => 'dell-xps-15',
                'description' => 'Premium Windows laptop with stunning OLED display',
                'short_description' => '15.6" OLED, Intel i7-13700H, 32GB RAM, 1TB SSD',
                'sku' => 'DELL-XPS15-I7',
                'price' => 195000.00,
                'compare_price' => 215000.00,
                'stock_quantity' => 12,
                'weight' => 1.8,
                'category_slug' => 'laptops',
            ],
            [
                'name' => 'HP Spectre x360',
                'slug' => 'hp-spectre-x360',
                'description' => 'Versatile 2-in-1 laptop with premium design',
                'short_description' => '13.5" touchscreen, Intel i7, 16GB RAM, 512GB SSD',
                'sku' => 'HP-SPX360-I7',
                'price' => 145000.00,
                'compare_price' => null,
                'stock_quantity' => 18,
                'weight' => 1.4,
                'category_slug' => 'laptops',
            ],
            [
                'name' => 'ASUS ROG Zephyrus',
                'slug' => 'asus-rog-zephyrus',
                'description' => 'Gaming laptop with RTX 4070 and high refresh display',
                'short_description' => '14" 144Hz, AMD Ryzen 9, RTX 4070, 16GB RAM',
                'sku' => 'ASUS-ROGZ-R9',
                'price' => 225000.00,
                'compare_price' => 245000.00,
                'stock_quantity' => 8,
                'weight' => 1.7,
                'category_slug' => 'laptops',
            ],
            
            // Tablets
            [
                'name' => 'Samsung Galaxy Tab S9 Ultra',
                'slug' => 'samsung-galaxy-tab-s9-ultra',
                'description' => 'Premium Android tablet with massive 14.6" display',
                'short_description' => '14.6" AMOLED, Snapdragon 8 Gen 2, S Pen included',
                'sku' => 'SAMSUNG-TS9U-512',
                'price' => 125000.00,
                'compare_price' => 145000.00,
                'stock_quantity' => 15,
                'weight' => 0.732,
                'category_slug' => 'tablets',
            ],
            [
                'name' => 'Microsoft Surface Pro 9',
                'slug' => 'microsoft-surface-pro-9',
                'description' => 'Professional tablet with laptop-grade performance',
                'short_description' => '13" touchscreen, Intel i7, 16GB RAM, 256GB SSD',
                'sku' => 'MSFT-SURF9-I7',
                'price' => 135000.00,
                'compare_price' => null,
                'stock_quantity' => 20,
                'weight' => 0.879,
                'category_slug' => 'tablets',
            ],
            
            // Accessories
            [
                'name' => 'JBL Tune 760NC',
                'slug' => 'jbl-tune-760nc',
                'description' => 'Wireless noise canceling headphones with great battery life',
                'short_description' => 'Wireless, ANC, 35hr battery, JBL Pure Bass',
                'sku' => 'JBL-T760NC-BLK',
                'price' => 8500.00,
                'compare_price' => 12000.00,
                'stock_quantity' => 150,
                'weight' => 0.268,
                'category_slug' => 'electronics-accessories',
            ],
            [
                'name' => 'Anker PowerCore 20000',
                'slug' => 'anker-powercore-20000',
                'description' => 'High-capacity power bank with fast charging support',
                'short_description' => '20000mAh, 22.5W fast charging, USB-C',
                'sku' => 'ANKER-PC20000',
                'price' => 3500.00,
                'compare_price' => 4500.00,
                'stock_quantity' => 200,
                'weight' => 0.435,
                'category_slug' => 'electronics-accessories',
            ],
            [
                'name' => 'Logitech MX Master 3S',
                'slug' => 'logitech-mx-master-3s',
                'description' => 'Premium wireless mouse for productivity and creative work',
                'short_description' => 'Wireless, 8000 DPI, Quiet clicks, 70-day battery',
                'sku' => 'LOGI-MXM3S-BLK',
                'price' => 9500.00,
                'compare_price' => null,
                'stock_quantity' => 80,
                'weight' => 0.141,
                'category_slug' => 'electronics-accessories',
            ],
            
            // Fashion
            [
                'name' => 'Adidas Ultraboost 22',
                'slug' => 'adidas-ultraboost-22',
                'description' => 'Premium running shoes with responsive Boost cushioning',
                'short_description' => 'Running shoes, Boost midsole, Primeknit upper',
                'sku' => 'ADIDAS-UB22-CBL',
                'price' => 15000.00,
                'compare_price' => 18000.00,
                'stock_quantity' => 120,
                'weight' => 0.31,
                'category_slug' => 'fashion',
            ],
            [
                'name' => 'Levi\'s 501 Original Fit Jeans',
                'slug' => 'levis-501-original-jeans',
                'description' => 'Classic straight-fit jeans in signature denim',
                'short_description' => 'Straight fit, 100% cotton, Button fly',
                'sku' => 'LEVIS-501-32W',
                'price' => 8500.00,
                'compare_price' => null,
                'stock_quantity' => 200,
                'weight' => 0.5,
                'category_slug' => 'fashion',
            ],
            [
                'name' => 'Ray-Ban Aviator Classic',
                'slug' => 'ray-ban-aviator-classic',
                'description' => 'Iconic aviator sunglasses with timeless style',
                'short_description' => 'Classic aviator, G-15 lenses, Gold frame',
                'sku' => 'RAYBAN-AVI-58',
                'price' => 12000.00,
                'compare_price' => 15000.00,
                'stock_quantity' => 60,
                'weight' => 0.045,
                'category_slug' => 'fashion',
            ],
            [
                'name' => 'Puma RS-X³',
                'slug' => 'puma-rs-x3',
                'description' => 'Retro-inspired sneakers with modern comfort',
                'short_description' => 'Lifestyle sneakers, RS foam tech, Bold design',
                'sku' => 'PUMA-RSX3-WHT',
                'price' => 9500.00,
                'compare_price' => 11000.00,
                'stock_quantity' => 150,
                'weight' => 0.35,
                'category_slug' => 'fashion',
            ],
            
            // Home & Living
            [
                'name' => 'IKEA POÄNG Armchair',
                'slug' => 'ikea-poang-armchair',
                'description' => 'Comfortable armchair with bentwood frame',
                'short_description' => 'Bentwood frame, High resilience foam, Washable cover',
                'sku' => 'IKEA-POANG-BRN',
                'price' => 12000.00,
                'compare_price' => 15000.00,
                'stock_quantity' => 25,
                'weight' => 12.5,
                'category_slug' => 'home-living',
            ],
            [
                'name' => 'Philips Hue Starter Kit',
                'slug' => 'philips-hue-starter-kit',
                'description' => 'Smart lighting system with color-changing bulbs',
                'short_description' => '2x A19 bulbs, Bridge, App control, 16M colors',
                'sku' => 'PHILIPS-HUE2',
                'price' => 8500.00,
                'compare_price' => 10000.00,
                'stock_quantity' => 80,
                'weight' => 0.8,
                'category_slug' => 'home-living',
            ],
            [
                'name' => 'Dyson V15 Detect',
                'slug' => 'dyson-v15-detect',
                'description' => 'Advanced cordless vacuum with laser dust detection',
                'short_description' => 'Cordless, Laser dust detection, 60min runtime, HEPA filter',
                'sku' => 'DYSON-V15-DET',
                'price' => 55000.00,
                'compare_price' => 60000.00,
                'stock_quantity' => 15,
                'weight' => 2.5,
                'category_slug' => 'home-living',
            ],
            [
                'name' => 'Instant Pot Duo 7-in-1',
                'slug' => 'instant-pot-duo-7in1',
                'description' => 'Multi-cooker with 7 cooking functions',
                'short_description' => '6Qt, 7-in-1, Pressure cooker, Slow cooker, Rice cooker',
                'sku' => 'INSTANT-DUO6QT',
                'price' => 8500.00,
                'compare_price' => 10000.00,
                'stock_quantity' => 60,
                'weight' => 5.4,
                'category_slug' => 'home-living',
            ],
            
            // Beauty & Personal Care
            [
                'name' => 'Dyson Airwrap Complete',
                'slug' => 'dyson-airwrap-complete',
                'description' => 'Multi-styler for hair without extreme heat',
                'short_description' => 'Complete set, Multiple barrels, Coanda effect, 30mm',
                'sku' => 'DYSON-AIRWRP',
                'price' => 45000.00,
                'compare_price' => 50000.00,
                'stock_quantity' => 20,
                'weight' => 0.68,
                'category_slug' => 'beauty-personal-care',
            ],
            [
                'name' => 'Philips Sonicare DiamondClean',
                'slug' => 'philips-sonicare-diamondclean',
                'description' => 'Premium electric toothbrush with multiple cleaning modes',
                'short_description' => '5 modes, USB charging, Travel case, 2 brush heads',
                'sku' => 'PHILIPS-SCDC',
                'price' => 12000.00,
                'compare_price' => null,
                'stock_quantity' => 45,
                'weight' => 0.45,
                'category_slug' => 'beauty-personal-care',
            ],
            [
                'name' => 'Foreo Luna 3 Plus',
                'slug' => 'foreo-luna-3-plus',
                'description' => 'Smart facial cleansing device with anti-aging technology',
                'short_description' => 'T-Sonic pulsations, Silicone brush, Firming massage',
                'sku' => 'FOREO-LUNA3P',
                'price' => 18500.00,
                'compare_price' => 22000.00,
                'stock_quantity' => 30,
                'weight' => 0.125,
                'category_slug' => 'beauty-personal-care',
            ],
            [
                'name' => 'Braun Series 9 Pro',
                'slug' => 'braun-series-9-pro',
                'description' => 'Premium electric shaver with advanced skin protection',
                'short_description' => '5-blade system, SyncroSonic, 60min battery, Wet & Dry',
                'sku' => 'BRAUN-S9PRO',
                'price' => 25000.00,
                'compare_price' => 28000.00,
                'stock_quantity' => 25,
                'weight' => 0.78,
                'category_slug' => 'beauty-personal-care',
            ],
            
            // Groceries
            [
                'name' => 'Nespresso Vertuo Next',
                'slug' => 'nespresso-vertuo-next',
                'description' => 'Premium coffee machine with versatile brewing options',
                'short_description' => 'Multiple cup sizes, Centrifusion technology, WiFi',
                'sku' => 'NESPRESSO-VNEXT',
                'price' => 18500.00,
                'compare_price' => 22000.00,
                'stock_quantity' => 35,
                'weight' => 4.8,
                'category_slug' => 'groceries',
            ],
            [
                'name' => 'Organic Honey 500g',
                'slug' => 'organic-honey-500g',
                'description' => 'Pure organic honey from certified farms',
                'short_description' => '100% organic, Raw honey, 500g jar',
                'sku' => 'HONEY-ORG500',
                'price' => 450.00,
                'compare_price' => 550.00,
                'stock_quantity' => 100,
                'weight' => 0.6,
                'category_slug' => 'groceries',
            ],
            [
                'name' => 'Extra Virgin Olive Oil 1L',
                'slug' => 'extra-virgin-olive-oil-1l',
                'description' => 'Premium cold-pressed olive oil from Mediterranean',
                'short_description' => 'Cold-pressed, First press, 1L bottle',
                'sku' => 'OLIVE-OIL-1L',
                'price' => 850.00,
                'compare_price' => null,
                'stock_quantity' => 80,
                'weight' => 1.2,
                'category_slug' => 'groceries',
            ],
            [
                'name' => 'Premium Coffee Beans 1kg',
                'slug' => 'premium-coffee-beans-1kg',
                'description' => 'Arabica coffee beans from high-altitude farms',
                'short_description' => '100% Arabica, Medium roast, 1kg bag',
                'sku' => 'COFFEE-ARAB1KG',
                'price' => 1200.00,
                'compare_price' => 1500.00,
                'stock_quantity' => 60,
                'weight' => 1.1,
                'category_slug' => 'groceries',
            ],
            
            // Sports & Outdoors
            [
                'name' => 'Yoga Mat Premium 6mm',
                'slug' => 'yoga-mat-premium-6mm',
                'description' => 'High-quality yoga mat with extra cushioning',
                'short_description' => '6mm thick, Non-slip, Eco-friendly, Carry strap',
                'sku' => 'YOGA-MAT6MM',
                'price' => 2500.00,
                'compare_price' => 3000.00,
                'stock_quantity' => 150,
                'weight' => 1.2,
                'category_slug' => 'sports-outdoors',
            ],
            [
                'name' => 'Dumbbell Set 20kg',
                'slug' => 'dumbbell-set-20kg',
                'description' => 'Adjustable dumbbell set with storage rack',
                'short_description' => '20kg total, Adjustable weights, Non-slip grip',
                'sku' => 'DUMBBELL-20KG',
                'price' => 8500.00,
                'compare_price' => 10000.00,
                'stock_quantity' => 40,
                'weight' => 20.5,
                'category_slug' => 'sports-outdoors',
            ],
            [
                'name' => 'Camping Tent 4-Person',
                'slug' => 'camping-tent-4-person',
                'description' => 'Waterproof camping tent for family adventures',
                'short_description' => '4-person, Waterproof, Easy setup, Carry bag',
                'sku' => 'TENT-4P-WTR',
                'price' => 6500.00,
                'compare_price' => 8000.00,
                'stock_quantity' => 30,
                'weight' => 4.2,
                'category_slug' => 'sports-outdoors',
            ],
            [
                'name' => 'Mountain Bike 26"',
                'slug' => 'mountain-bike-26',
                'description' => 'All-terrain mountain bike with 21 speeds',
                'short_description' => '26" wheels, 21 speeds, Disc brakes, Aluminum frame',
                'sku' => 'MTB-26-AL',
                'price' => 18500.00,
                'compare_price' => 22000.00,
                'stock_quantity' => 12,
                'weight' => 15.5,
                'category_slug' => 'sports-outdoors',
            ],
            
            // Books & Media
            [
                'name' => 'Kindle Paperwhite 11th Gen',
                'slug' => 'kindle-paperwhite-11th',
                'description' => 'Waterproof e-reader with adjustable warm light',
                'short_description' => '6.8" display, Waterproof, 8GB storage, USB-C',
                'sku' => 'KINDLE-PW11-8GB',
                'price' => 12500.00,
                'compare_price' => 15000.00,
                'stock_quantity' => 45,
                'weight' => 0.205,
                'category_slug' => 'books-media',
            ],
            [
                'name' => 'Bluetooth Speaker Waterproof',
                'slug' => 'bluetooth-speaker-waterproof',
                'description' => 'Portable waterproof speaker with 360° sound',
                'short_description' => 'IPX7 waterproof, 20W output, 12hr battery, RGB lights',
                'sku' => 'BTSPK-WTR20W',
                'price' => 3500.00,
                'compare_price' => 4500.00,
                'stock_quantity' => 120,
                'weight' => 0.45,
                'category_slug' => 'books-media',
            ],
            [
                'name' => '4K Webcam Pro',
                'slug' => '4k-webcam-pro',
                'description' => 'Professional webcam with 4K resolution and auto-focus',
                'short_description' => '4K 30fps, Auto-focus, Noise cancellation, Wide angle',
                'sku' => 'WEBCAM-4KPRO',
                'price' => 6500.00,
                'compare_price' => 8000.00,
                'stock_quantity' => 70,
                'weight' => 0.32,
                'category_slug' => 'books-media',
            ],
            [
                'name' => 'Wireless Gaming Mouse',
                'slug' => 'wireless-gaming-mouse',
                'description' => 'High-precision gaming mouse with RGB lighting',
                'short_description' => '16000 DPI, RGB lighting, Programmable buttons',
                'sku' => 'GAMOUSE-WRLS',
                'price' => 3500.00,
                'compare_price' => 4500.00,
                'stock_quantity' => 90,
                'weight' => 0.12,
                'category_slug' => 'books-media',
            ],
            
            // Toys & Games
            [
                'name' => 'LEGO Creator Expert',
                'slug' => 'lego-creator-expert',
                'description' => 'Advanced LEGO set for experienced builders',
                'short_description' => '1000+ pieces, Detailed instructions, Display model',
                'sku' => 'LEGO-CREXP-1000',
                'price' => 8500.00,
                'compare_price' => 10000.00,
                'stock_quantity' => 35,
                'weight' => 1.8,
                'category_slug' => 'toys-games',
            ],
            [
                'name' => 'Remote Control Car 1:10',
                'slug' => 'remote-control-car-1-10',
                'description' => 'High-speed RC car with off-road capabilities',
                'short_description' => '1:10 scale, 4WD, 30km/h, Rechargeable battery',
                'sku' => 'RCCAR-1-10-4WD',
                'price' => 6500.00,
                'compare_price' => 8000.00,
                'stock_quantity' => 45,
                'weight' => 2.1,
                'category_slug' => 'toys-games',
            ],
            [
                'name' => 'Board Game Collection',
                'slug' => 'board-game-collection',
                'description' => 'Set of classic board games for family fun',
                'short_description' => '5 games included, Family-friendly, Ages 8+',
                'sku' => 'BOARDGAME-COL5',
                'price' => 2500.00,
                'compare_price' => 3000.00,
                'stock_quantity' => 80,
                'weight' => 1.5,
                'category_slug' => 'toys-games',
            ],
            [
                'name' => 'Drone with 4K Camera',
                'slug' => 'drone-with-4k-camera',
                'description' => 'Professional drone with stabilized 4K camera',
                'short_description' => '4K camera, GPS, 25min flight time, Return to home',
                'sku' => 'DRONE-4K-GPS',
                'price' => 18500.00,
                'compare_price' => 22000.00,
                'stock_quantity' => 20,
                'weight' => 0.85,
                'category_slug' => 'toys-games',
            ],
            
            // Computer
            [
                'name' => 'Gaming Mechanical Keyboard',
                'slug' => 'gaming-mechanical-keyboard',
                'description' => 'RGB mechanical keyboard for gaming and typing',
                'short_description' => 'Mechanical switches, RGB backlight, Programmable keys',
                'sku' => 'KB-MECH-RGB',
                'price' => 5500.00,
                'compare_price' => 7000.00,
                'stock_quantity' => 60,
                'weight' => 1.2,
                'category_slug' => 'computer',
            ],
            [
                'name' => '4K Monitor 27"',
                'slug' => '4k-monitor-27',
                'description' => 'Ultra HD monitor with HDR support',
                'short_description' => '27" 4K, IPS panel, HDR400, USB-C hub',
                'sku' => 'MONITOR-4K27',
                'price' => 18500.00,
                'compare_price' => 22000.00,
                'stock_quantity' => 25,
                'weight' => 5.5,
                'category_slug' => 'computer',
            ],
            [
                'name' => 'External SSD 1TB',
                'slug' => 'external-ssd-1tb',
                'description' => 'Portable solid-state drive with fast transfer speeds',
                'short_description' => '1TB capacity, USB-C, 1050MB/s, Shock resistant',
                'sku' => 'SSD-EXT1TB',
                'price' => 8500.00,
                'compare_price' => 10000.00,
                'stock_quantity' => 75,
                'weight' => 0.05,
                'category_slug' => 'computer',
            ],
            [
                'name' => 'Graphics Card RTX 4060',
                'slug' => 'graphics-card-rtx-4060',
                'description' => 'High-performance graphics card for gaming',
                'short_description' => 'RTX 4060, 8GB GDDR6, DLSS 3, Ray tracing',
                'sku' => 'GPU-RTX4060',
                'price' => 35000.00,
                'compare_price' => 40000.00,
                'stock_quantity' => 15,
                'weight' => 0.85,
                'category_slug' => 'computer',
            ],
        ];

        foreach ($additionalProducts as $productData) {
            $category = Category::where('slug', $productData['category_slug'])->first();
            
            if (!$category) {
                echo "Warning: Category '{$productData['category_slug']}' not found for product '{$productData['name']}'. Skipping...\n";
                continue;
            }
            
            // Check if product already exists to avoid duplicates
            $existingProduct = Product::where('sku', $productData['sku'])->first();
            if ($existingProduct) {
                echo "Product '{$productData['name']}' (SKU: {$productData['sku']}) already exists. Skipping...\n";
                continue;
            }
            
            $product = Product::create([
                'name' => $productData['name'],
                'slug' => $productData['slug'],
                'description' => $productData['description'],
                'short_description' => $productData['short_description'],
                'sku' => $productData['sku'],
                'price' => $productData['price'],
                'compare_price' => $productData['compare_price'],
                'stock_quantity' => $productData['stock_quantity'],
                'weight' => $productData['weight'],
                'category_id' => $category->id,
                'is_active' => true,
                'is_featured' => rand(0, 3) == 1, // 25% chance of being featured
                'sort_order' => rand(1, 100),
                'track_stock' => true,
            ]);

            // Create product images
            ProductImage::create([
                'product_id' => $product->id,
                'image_path' => 'https://via.placeholder.com/400x400',
                'alt_text' => $product->name,
                'sort_order' => 1,
                'is_primary' => true,
            ]);
            
            echo "Created product: {$product->name}\n";
        }
        
        echo "\nSuccessfully added " . count($additionalProducts) . " additional products!\n";
    }
}
